# Generated by Django 3.1.6 on 2021-02-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[
                 ('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='small', max_length=6)),
                ('name', models.CharField(choices=[('margarita', 'margarita'), (
                    'diavolo', 'diavolo'), ('tonno', 'tonno')], default='tonno', max_length=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='pizzas', to='boards.order')),
            ],
        ),
    ]
