# Generated by Django 3.1.6 on 2021-02-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210203_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='customer_exmample', max_length=30),
        ),
    ]
