# Generated by Django 3.1.6 on 2021-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20210203_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(max_length=30)),
                ('order_email', models.CharField(max_length=30)),
                ('orderer', models.CharField(default='customer_exmample', max_length=30)),
                ('order_size', models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='small', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='PizzaOrder',
        ),
    ]
