# Generated by Django 3.1.6 on 2021-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210203_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorderinfo',
            name='pizza_name',
            field=models.CharField(choices=[('diavolor', 'diavolor'), ('salami', 'salami'), ('margarita', 'margarita')], default='diavolo', max_length=10),
        ),
    ]
