# Generated by Django 3.1.6 on 2021-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_pizzaorderinfo_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorderinfo',
            name='pizza_name',
            field=models.CharField(choices=[('diavolo', 'diavolo'), ('salami', 'salami'), ('margarita', 'margarita')], default='diavolo', max_length=10),
        ),
    ]
