# Generated by Django 3.1.6 on 2021-02-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210203_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaOrderInfo',
            new_name='Pizza',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='order_address',
            new_name='pizza_order_address',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='order_email',
            new_name='pizza_order_email',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='order_size',
            new_name='pizza_order_size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='orderer',
            new_name='pizza_orderer',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_name',
            new_name='pizza_variation',
        ),
    ]
