# Generated by Django 3.1.6 on 2021-02-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20210203_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Order',
        ),
    ]
