# Generated by Django 3.1.6 on 2021-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20210203_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_order_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_order_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_orderer',
            field=models.CharField(default='customer_exmample', max_length=255),
        ),
    ]
