# Generated by Django 3.1.6 on 2021-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20210203_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_order_email',
            field=models.EmailField(max_length=255),
        ),
    ]
